export  const GET_POKEMONS_REQUESTED = 'GET_POKEMONS_REQUESTED';

export  const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export  const GET_POKEMON_CARD_INFO_SUCCESS = 'GET_POKEMON_CARD_INFO_SUCCESS';

export  const GET_POKEMONS_FAILED = 'GET_POKEMONS_FAILED';

export  const CLEAR_POKEMONS = 'CLEAR_POKEMONS';
